project:
  type: website
  output-dir: gh-pages

website:
  title: "Chris Thinks"
  navbar:
    right:
      - icon: github
        href: https://github.com/chrischcodes
  site-url: https://christhinks.github.io/
  google-analytics: G-BMK1V40GJ4
  twitter-card: true
  open-graph: true

format:
  html:
    theme: spacelab
    css: styles.css

